### ISSUE TITLE
ClassCastException with LG Devices

### ISSUE THREAD

**Issue by kosratdev** [davcpas1234/MaterialSettings#17]
Hi, 

**My firebase crash reporting reports this error:** 
`Exception java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout
com.kosratdahmad.myprayers.activities.SettingsActivity.setUpNestedScreen (SettingsActivity.java)
com.kosratdahmad.myprayers.activities.SettingsActivity.onPreferenceTreeClick (SettingsActivity.java)
android.preference.Preference.performClick (Preference.java:1005)
android.preference.PreferenceScreen.onItemClick (PreferenceScreen.java:214)
android.widget.AdapterView.performItemClick (AdapterView.java:310)
android.widget.AbsListView.performItemClick (AbsListView.java:1199)
android.widget.AbsListView$PerformClick.run (AbsListView.java:3171)
android.widget.AbsListView$3.run (AbsListView.java:4225)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6247)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)`

**This code makes this error only in LG G5 and LG V20 on api level 24:**
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            LinearLayout root = (LinearLayout) dialog.findViewById(android.R.id.list).getParent();
            appBar = (AppBarLayout) LayoutInflater.from(this).inflate(R.layout.toolbar_settings, root, false);
            root.addView(appBar, 0);
        }`

**I tested on Nexus 5X api level 24 and 25 it works fine and I don't know why makes this error on LG devices**

**Comment by gcstang** [comment]
I've recently come across this same issue even though I'm using your awesome post from Stack Overflow.

API Level 24
LG-H915
Locale: en-CA
Android OS: 7.0

java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout

**Comment by iori57** [comment]
Hi, did anyone has a fix for this one yet since it was raised back in January? Only recently I get lots of crash reports for this issue on all LG devices and unhappy LG users sending me email asking for a fix :)

I can't troubleshoot the problem because I don't have a LG device with me :( I used to be a LG user myself but it went into bootloop :(

Btw here is the distribution of the affected LG devices:
V20 (elsa) | 18 | 29.5%
LG G6 (lucye) | 16 | 26.2%
LG Stylo 2 Plus (ph2n) | 9 | 14.8%
LG Stylo 2 (ph1) | 6 | 9.8%
LG K8 (lv3) | 5 | 8.2%
LG K10 (m209n) | 3 | 4.9%
LG Stylo3 (sf340) | 2 | 3.3%
LG Escape 3 (m1v) | 1 | 1.6%
LG G Pad III 8.0 FHD (b3) | 1 | 1.6%

And all of them are on Android 7.0

**Comment by kosratdev** [comment]
Hi @iori57 

I have pull requested to resolve this issue

**Comment by iori57** [comment]
Thank you so much!

Just saw your fix, I like the way you approach the problem :) I agree the behaviour is too hard to predict and sometimes we have to do it with brute force
